name: Deploy Docker Image

on:
  release:
    types:
      - published

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build -t artis3n/docker-ubuntu1804-ansible .
    - name: Deploy the Docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: artis3n/docker-ubuntu1804-ansible
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_password }}
        tag_names: true
